import {
	Activity,
	Archive,
	ArrowRightLeft,
	Bell,
	BookOpen,
	Boxes,
	CalendarClock,
	CircleArrowUp,
	CircleQuestionMark,
	CircleUserRound,
	Clapperboard,
	CloudUpload,
	Container,
	Cpu,
	Eraser,
	Feather,
	File,
	FileInput,
	FileText,
	FolderOpen,
	Gauge,
	GitBranch,
	GitPullRequest,
	Globe,
	Hammer,
	HardDrive,
	Images,
	KeyRound,
	Layers,
	LayoutDashboard,
	LayoutTemplate,
	LifeBuoy,
	ListChecks,
	Lock,
	LogIn,
	Network,
	Rocket,
	RotateCcw,
	ScanSearch,
	ScrollText,
	Server,
	Settings2,
	Share2,
	ShieldCheck,
	Signpost,
	Terminal,
	Upload,
	UserCog,
	Users,
	Variable,
	Webhook,
} from "@lucide/svelte";

// Guide slugs are shared across projects where they mean the same thing (getting-started,
// showcase, notifications). Guides synced from a repo later fall back to a plain file icon.
const ICONS = {
	overview: BookOpen,
	"getting-started": Rocket,
	showcase: Images,
	notifications: Bell,
	// homerun
	configuration: Settings2,
	"faq-and-limitations": CircleQuestionMark,
	services: Container,
	"deploy-source-and-builds": Hammer,
	"git-providers": GitBranch,
	"deploy-on-push": Webhook,
	"pull-request-previews": GitPullRequest,
	"status-checks": ListChecks,
	"compose-import": FileInput,
	"migrating-from-dokploy-or-coolify": ArrowRightLeft,
	deploying: CloudUpload,
	"revisions-and-rollback": RotateCcw,
	"image-scanning": ScanSearch,
	"env-vars": Variable,
	networking: Network,
	"dns-automation": Signpost,
	"runtime-and-compute": Cpu,
	"swarm-mode": Boxes,
	observability: Activity,
	scheduling: CalendarClock,
	stacks: Layers,
	templates: LayoutTemplate,
	"storage-volumes": HardDrive,
	backups: Archive,
	"remote-hosts-and-agent": Server,
	"users-and-roles": Users,
	"authentication-providers": KeyRound,
	"your-profile": CircleUserRound,
	"two-factor-and-passkeys": ShieldCheck,
	"login-wall": Lock,
	"sign-in-with-homerun": LogIn,
	dashboard: LayoutDashboard,
	"system-logs": ScrollText,
	"docker-cleanup": Eraser,
	"status-pages": Gauge,
	upgrading: CircleArrowUp,
	"api-and-cli": Terminal,
	// penombre
	env: Variable,
	deployment: Server,
	storage: HardDrive,
	uploads: Upload,
	volumes: Layers,
	sharing: Share2,
	"shared-drives": FolderOpen,
	documents: FileText,
	media: Clapperboard,
	admin: UserCog,
	"simple-mode": Feather,
	"reverse-proxy": Globe,
	troubleshooting: LifeBuoy,
	authentication: KeyRound,
	architecture: Boxes,
};

export const guideIcon = (slug: string) => ICONS[slug as keyof typeof ICONS] ?? File;
