import {
	Archive,
	Bell,
	BookOpen,
	Boxes,
	CircleQuestionMark,
	Clapperboard,
	Container,
	Feather,
	File,
	FileText,
	FolderOpen,
	FolderTree,
	Globe,
	HardDrive,
	Images,
	KeyRound,
	Layers,
	LifeBuoy,
	Network,
	Rocket,
	Server,
	Settings2,
	Share2,
	Terminal,
	Upload,
	UserCog,
	Users,
	Variable,
	Wrench,
} from "@lucide/svelte";

// Guide slugs are shared across projects where they mean the same thing (getting-started,
// showcase, storage). Guides synced from a repo later fall back to a plain file icon.
const ICONS = {
	overview: BookOpen,
	"getting-started": Rocket,
	showcase: Images,
	// homerun
	configuration: Settings2,
	services: Container,
	"stacks-and-templates": FolderTree,
	"remote-hosts-and-agent": Network,
	"users-and-access": Users,
	"storage-and-backups": Archive,
	operations: Wrench,
	"api-and-cli": Terminal,
	"faq-and-limitations": CircleQuestionMark,
	// penombre
	env: Variable,
	deployment: Server,
	storage: HardDrive,
	uploads: Upload,
	volumes: Layers,
	sharing: Share2,
	"shared-drives": FolderOpen,
	documents: FileText,
	media: Clapperboard,
	notifications: Bell,
	admin: UserCog,
	"simple-mode": Feather,
	"reverse-proxy": Globe,
	troubleshooting: LifeBuoy,
	authentication: KeyRound,
	architecture: Boxes,
};

export const guideIcon = (slug: string) => ICONS[slug as keyof typeof ICONS] ?? File;
