// `bun run screenshots`: refetch the Penombre gallery and re-encode it.
//
// The files already in src/screenshots are the list: every <name>.webp is
// re-fetched from <SOURCE>/<name>.png, so adding a shot to the page means
// putting its name here once and letting this keep it current. Upstream is
// generated by Playwright in the Penombre repo and published with its docs;
// .github/workflows/screenshots.yml runs this daily and commits what moved.
import { Glob } from "bun";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const SOURCE = "https://penombre.orochibraru.com/docs-images";
const DIR = "src/screenshots";
const WIDTH = 1200; // twice the widest the page ever displays one
const QUALITY = 80;

if (!Bun.which("cwebp")) {
  console.error("cwebp not found: brew install webp, or apt-get install webp");
  process.exit(1);
}

const names = [...new Glob("*.webp").scanSync(DIR)]
  .map((file) => file.replace(/\.webp$/, ""))
  .sort();

if (!names.length) throw new Error(`${DIR} is empty, so there is nothing to refresh`);

const scratch = await mkdtemp(join(tmpdir(), "gallery-"));
const changed: string[] = [];
const failed: string[] = [];

for (const name of names) {
  const response = await fetch(`${SOURCE}/${name}.png`);
  if (!response.ok) {
    failed.push(`${name}: ${response.status} ${response.statusText}`);
    continue;
  }

  const png = join(scratch, `${name}.png`);
  await Bun.write(png, response);

  const destination = `${DIR}/${name}.webp`;
  const before = await Bun.file(destination).bytes().catch(() => new Uint8Array());
  const encoded = join(scratch, `${name}.webp`);
  const run = Bun.spawnSync([
    "cwebp", "-quiet", "-q", String(QUALITY), "-resize", String(WIDTH), "0", png, "-o", encoded,
  ]);
  if (run.exitCode !== 0) {
    failed.push(`${name}: cwebp exited ${run.exitCode}`);
    continue;
  }

  const after = await Bun.file(encoded).bytes();
  if (before.length === after.length && Buffer.from(before).equals(after)) continue;

  await Bun.write(destination, after);
  changed.push(`${name} (${Math.round(after.length / 1024)}KB)`);
}

await rm(scratch, { recursive: true, force: true });

console.log(`${names.length} shot(s) checked, ${changed.length} changed`);
for (const line of changed) console.log(`  updated ${line}`);
for (const line of failed) console.error(`  FAILED  ${line}`);

process.exit(failed.length ? 1 : 0);
