// `bun run dev`: build, serve what was built, rebuild when a source file changes.
//
// It serves dist/ rather than src/ because Bun's dev server hands .html entry
// documents to the browser without running bundler plugins over them, so the
// #includes in src/ would still be comments there. It does reload a file it
// serves when that file changes on disk, which is exactly what a rebuild does:
// edit a page, the browser catches up on its own a second later.
import { watch } from "node:fs";
import { Glob } from "bun";
import { log, VERBOSE } from "./log";

const out = log("dev");

// The first build is the interesting one — it says what the site is made of.
// Every rebuild after it is noise in a watch loop, so those run QUIET, which
// leaves the build printing its one summary line. This prints what triggered
// it, before the work, so the pair reads as cause and effect.
function build(reason?: string) {
  if (reason) out.step(reason);

  const run = Bun.spawnSync(["bun", "run", "scripts/build.ts"], {
    stdout: "inherit",
    stderr: "inherit",
    env: reason ? { ...process.env, QUIET: "1" } : process.env,
  });

  // Not fatal: the last good dist/ is still on disk and still being served, so
  // fix the file and save again rather than restarting.
  if (run.exitCode !== 0) out.fail(`build failed (exit ${run.exitCode}) — serving the last good build`);
}

build();

const pages = [...new Glob("dist/**/*.html").scanSync(".")];
const server = Bun.spawn(["bun", ...pages], { stdout: "inherit", stderr: "inherit" });

out.info(`watching src/ — ${pages.length} page(s) served`);
if (!VERBOSE) out.info("VERBOSE=1 for the full build output on every rebuild");

// What the build writes back into src/: watching these would rebuild forever.
const GENERATED = /^(blog|[^/]+\/docs)(\/|$)/;

// A source file, by extension. Two reasons to insist on one:
//
// The build copies src/docs/<project>/images into dist/, and on macOS a
// recursive fs.cp raises a `rename` event on the *source* directory. That event
// names a directory, not a file, and GENERATED doesn't cover src/docs — so
// without this every build triggered the next one, forever.
//
// It also drops the swap and backup files an editor leaves next to the real one.
const SOURCE = /\.(html|css|js|md|txt|jpe?g|webp|svg|ico)$/;

let queued: ReturnType<typeof setTimeout> | undefined;
let pending = new Set<string>();

watch("src", { recursive: true }, (_event, file) => {
  if (typeof file !== "string") return;
  if (GENERATED.test(file)) {
    out.detail(`ignored ${file} (generated by the build)`);
    return;
  }
  if (!SOURCE.test(file)) {
    out.detail(`ignored ${file} (not a source file)`);
    return;
  }

  pending.add(file);
  clearTimeout(queued);
  queued = setTimeout(() => {
    // One save often fires several events; report the batch, not each event.
    const changed = [...pending];
    pending = new Set();
    const reason = changed.length === 1 ? `${changed[0]} changed` : `${changed.length} files changed`;
    for (const name of changed) out.detail(`changed ${name}`);
    build(reason);
  }, 50);
});

process.on("SIGINT", () => {
  out.info("stopping");
  server.kill();
  process.exit(0);
});
